second_time/second_app/urls.py
from django.conf.urls import url
from second_app import views
app_name = 'second_app'

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^user_logout/', views.user_logout,name='user_logout'),
    url(r'^registration/', views.registration_view,name='registration_view'),
    url(r'^cbview/', views.CBView.as_view(),name='cbview'),
    url(r'^template_view/', views.TemplatePageView.as_view(),name='template_view'),
    url(r'^school_list_view/', views.SchoolListView.as_view(),name='school_list_view'),
    url(r'^school/(?P<pk>\d+)/$', views.SchoolDetailView.as_view(),name='school_detail_view'),
    url(r'^school_create/$', views.SchoolCreateView.as_view(),name='school_create_view'),
    url(r'^student_create/$', views.StudentCreateView.as_view(),name='student_create_view'),    
    url(r'^school_update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(),name='school_update_view'),
    url(r'^school_delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(),name='school_delete_view'),

]

second_time/second_time/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from second_app import views
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^user_login/$', views.user_login,name='user_login'),
    url(r'^second_app/',include('second_app.urls')),
    url(r'^admin/', admin.site.urls),
]

second_time/second_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    url = models.CharField(max_length=264)
    profile_pic = models.ImageField(upload_to = 'profile_pic', blank =True)

    def __str__(self):
        return self.user.username

class School(models.Model):
    name = models.CharField(max_length = 264)
    principal = models.CharField(max_length = 264)
    location = models.CharField(max_length = 264)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("second_app:school_detail_view", kwargs={"pk": self.pk})
    
class Student(models.Model):
    name = models.CharField(max_length = 264)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("second_app:school_list_view")
    

second_time/second_app/forms.py
from django import forms
from django.contrib.auth.models import User
from second_app.models import UserProfileInfo
class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')
    

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('url','profile_pic')

second_time/second_app/views.py
from django.shortcuts import render
from second_app.models import UserProfileInfo,School,Student
from second_app.forms import UserForm,UserProfileInfoForm


from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
# Create your views here.

def index(request):
    return render(request,'second_app/index.html')

def registration_view(request):
        registered = False
        if request.method == 'POST':
                user_form = UserForm(data=request.POST)
                user_profile_info_form = UserProfileInfoForm(data=request.POST)
                if user_form.is_valid() and user_profile_info_form.is_valid():
                        user = user_form.save()
                        user.set_password(user.password)
                        user.save()

                        profile = user_profile_info_form.save(commit=False)
                        profile.user = user
                        if 'profile_pic' in request.FILES:
                                profile.profile_pic = request.FILES['profile_pic']
                        profile.save()
                        registered =True
                        return index(request)
        else:
                user_form = UserForm()
                user_profile_info_form = UserProfileInfoForm()
        return render(request,'second_app/registration.html',{'user_form':user_form,
                                                                'user_profile_info_form':user_profile_info_form,
                                                                'registered':registered})

def user_login(request):
        if request.method == 'POST':
                email = request.POST.get('email')
                password = request.POST.get('password')

                user = authenticate(username=email, password=password)
                if user:
                        if user.is_active:
                                login(request,user)
                                return HttpResponseRedirect(reverse('index'))
                        else:
                                return HttpResponse('Account not active')
                else:
                        return HttpResponse('invalid credentials')
        else:
                return render(request,'second_app/login.html')
        return render(request,'second_app/login.html')

@login_required
def user_logout(request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))


        return render(request,'second_app/login.html')


class CBView(View):
        def get(self,request):
                return HttpResponse("This is the class based view page")

class TemplatePageView(TemplateView):
        template_name = 'second_app/template_view_test.html'
        
        def get_context_data(self,**kwargs):
                context = super().get_context_data(**kwargs)
                context['inject_me'] = "Injected Content for Template view page"
                return context

class SchoolListView(ListView):
        model = School
        template_name = 'second_app/school_list_page.html'

class SchoolDetailView(DetailView):
        model = School
        template_name = 'second_app/school_detail.html'
        context_object_name = 'school_detail'

class SchoolCreateView(CreateView):
        model =School
        fields = ('name','principal','location')

class StudentCreateView(CreateView):
        model =Student
        fields = ('name','age','school')
class SchoolUpdateView(UpdateView):
        model = School
        fields = ('name','principal')

class SchoolDeleteView(DeleteView):
        model = School
        success_url = reverse_lazy('second_app:school_list_view')

second_time/templates/second_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href='{% static "css/form_style.css" %}'>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="#">Active</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'second_app:registration_view'%}">Form Page</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'second_app:user_logout' %}">Logout</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'second_app:cbview' %}">ClassBasedView</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'second_app:template_view' %}">TemplateTestview</a>
            </li>
        {%else%}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_login' %}">Login</a>
            </li>
        {%endif%}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index'%}">Admin</a>
        </li>
    </ul>
    {% block body_block %}
    {% endblock%}
</body>
</html>

second_time/templates/second_app/form_page.html
<!DOCTYPE html>
{% extends 'second_app/base.html' %}
{% block body_block %}
    <h1 class="red">This is the Form page</h1>
    <div class="form_div">
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

second_time/templates/second_app/index.html
<!DOCTYPE html>
{% extends 'second_app/base.html' %}
{% block body_block %}
    <h1>This is from second app index</h1>
    <h3>This is FF Gamers official website</h3>
    {% if users %}
        {% for user in users %}
            <ul>
                <li>{{user.first_name}}</li>
                <li>{{user.last_name}}</li>
            </ul>
        {% endfor %}
    {% else %}
        <h3>No user</h3>
    {% endif %}
{% endblock %}

second_time/templates/second_app/login.html
{% extends 'second_app/base.html' %}
{% block body_block %}
    <form action="{% url 'user_login'%}" method="POST">
        {% csrf_token %}
        <input type="text" name="email" placeholder="Email">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>
{% endblock%}

second_time/templates/second_app/registration.html
{% extends 'second_app/base.html'%}
{% block body_block %}
{% if registered %}
    <h3>Already registered</h3>
{% else %}
    <h3>Fill this registration form</h3>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{user_form.as_p}}
        {{user_profile_info_form.as_p}}
        <input type="submit" value="Register">
    </form>
{% endif %}

{% endblock %}

second_time/templates/second_app/school_confirm_delete.html
{% extends 'second_app/base.html'%}
{% block body_block %}
    <p>Delete {{school.name}}?</p>
    <form method="POST">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Delete">
        <a href="{% url 'second_app:school_detail_view' pk=school.pk %}">Cancel</a>

    </form>
    
{% endblock%}

second_time/templates/second_app/school_detail.html
{% extends 'second_app/base.html' %}
{% block body_block%}
    <h1>School Detail Page</h1>
    <h3>Name : {{school_detail.name}}</h3>
    <h3>Principal : {{school_detail.principal}}</h3>
    <h3>Location : {{school_detail.location}}</h3>

    <h2>List of students in {{school_detail.name}}</h2>
    {% for student in school_detail.students.all%}
        <ul>
            <li>{{student.name}} of {{student.age}} years old</li>
        </ul>
    {% endfor%}
    <a class="btn btn-warning" href="{% url 'second_app:school_update_view' pk=school_detail.pk %}">Update</a>
    <a class="btn btn-danger" href="{% url 'second_app:school_delete_view' pk=school_detail.pk %}">Delete</a>

{% endblock%}

second_time/templates/second_app/school_form.html
{% extends 'second_app/base.html'%}
{% block body_block%}
    {% if not form.instance.pk%}
        Create School
    {% else %}
        Update School
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock%}

second_time/templates/second_app/school_list_page.html
{% extends 'second_app/base.html'%}
{% block body_block%}
    {% for school in school_list %}
        <ul>
            <li><a href = "{% url 'second_app:school_detail_view' pk=school.id%}">{{school.name}}</a></li>
        </ul>
    {% endfor%}
{% endblock%}

second_time/templates/second_app/student_form.html
{% extends 'second_app/base.html'%}
{% block body_block%}
    {% if not form.instance.pk%}
        Create Student
    {% else%}
        Update Student
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock%}

second_time/templates/second_app/template_view_test.html
{% extends 'second_app/base.html' %}
{% block body_block%}
<h3>This is the Template View Testing Page</h3>
{{inject_me}}
{% endblock%}